services:
  ai_app:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    container_name: ${CONTAINER_NAME}
    volumes:
      - ./src:/app/src
      - ./models:/app/models
      - ./data:/app/data
      - ./outputs:/app/outputs
      - ./scripts:/app/scripts
    entrypoint: ["tail", "-f", "/dev/null"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: ${GPU_DEVICE}
              capabilities: [gpu]
