services:
  ai_app:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    container_name: ${CONTAINER_NAME}
    volumes:
      - ./src:/home/appuser/app/src
      - ./models:/home/appuser/app/models
      - ./data:/home/appuser/app/data
      - ./outputs:/home/appuser/app/outputs
      - ./scripts:/home/appuser/app/scripts
    entrypoint: ["tail", "-f", "/dev/null"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: ${GPU_DEVICE}
              capabilities: [gpu]
